name: DevSecOps Pipeline

on:
  push:
    branches: [ main, feature/* ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # SAST - CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # SBOM + SCA
      - name: Generate SBOM
        run: npx @cyclonedx/cyclonedx-npm --output-format json --output-file sbom.json .

      - name: Scan vulnerabilities with Grype
        uses: anchore/scan-action@v3
        with:
          sbom: sbom.json
          severity-cutoff: medium
          output-format: table